// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.2
// source: ssosage.proto

package ssosage_proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Ssosage_RegisterApp_FullMethodName    = "/ssosage_proto.Ssosage/RegisterApp"
	Ssosage_RegisterClient_FullMethodName = "/ssosage_proto.Ssosage/RegisterClient"
	Ssosage_GenerateToken_FullMethodName  = "/ssosage_proto.Ssosage/GenerateToken"
)

// SsosageClient is the client API for Ssosage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SsosageClient interface {
	// add information about application roles, secret and name - name is unique identifier
	RegisterApp(ctx context.Context, in *RegisterAppRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// creates user/client with one role per registered app
	//
	//	(what if app was registered after client registration? client will need to add the role I guess)
	RegisterClient(ctx context.Context, in *RegisterClientRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// generates jwt token that is signed with app secret and contains map app_name -> role
	GenerateToken(ctx context.Context, in *GenerateTokenRequest, opts ...grpc.CallOption) (*GenerateTokenResponse, error)
}

type ssosageClient struct {
	cc grpc.ClientConnInterface
}

func NewSsosageClient(cc grpc.ClientConnInterface) SsosageClient {
	return &ssosageClient{cc}
}

func (c *ssosageClient) RegisterApp(ctx context.Context, in *RegisterAppRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Ssosage_RegisterApp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ssosageClient) RegisterClient(ctx context.Context, in *RegisterClientRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Ssosage_RegisterClient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ssosageClient) GenerateToken(ctx context.Context, in *GenerateTokenRequest, opts ...grpc.CallOption) (*GenerateTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateTokenResponse)
	err := c.cc.Invoke(ctx, Ssosage_GenerateToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SsosageServer is the server API for Ssosage service.
// All implementations must embed UnimplementedSsosageServer
// for forward compatibility.
type SsosageServer interface {
	// add information about application roles, secret and name - name is unique identifier
	RegisterApp(context.Context, *RegisterAppRequest) (*emptypb.Empty, error)
	// creates user/client with one role per registered app
	//
	//	(what if app was registered after client registration? client will need to add the role I guess)
	RegisterClient(context.Context, *RegisterClientRequest) (*emptypb.Empty, error)
	// generates jwt token that is signed with app secret and contains map app_name -> role
	GenerateToken(context.Context, *GenerateTokenRequest) (*GenerateTokenResponse, error)
	mustEmbedUnimplementedSsosageServer()
}

// UnimplementedSsosageServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSsosageServer struct{}

func (UnimplementedSsosageServer) RegisterApp(context.Context, *RegisterAppRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterApp not implemented")
}
func (UnimplementedSsosageServer) RegisterClient(context.Context, *RegisterClientRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterClient not implemented")
}
func (UnimplementedSsosageServer) GenerateToken(context.Context, *GenerateTokenRequest) (*GenerateTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateToken not implemented")
}
func (UnimplementedSsosageServer) mustEmbedUnimplementedSsosageServer() {}
func (UnimplementedSsosageServer) testEmbeddedByValue()                 {}

// UnsafeSsosageServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SsosageServer will
// result in compilation errors.
type UnsafeSsosageServer interface {
	mustEmbedUnimplementedSsosageServer()
}

func RegisterSsosageServer(s grpc.ServiceRegistrar, srv SsosageServer) {
	// If the following call pancis, it indicates UnimplementedSsosageServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Ssosage_ServiceDesc, srv)
}

func _Ssosage_RegisterApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterAppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SsosageServer).RegisterApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ssosage_RegisterApp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SsosageServer).RegisterApp(ctx, req.(*RegisterAppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ssosage_RegisterClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SsosageServer).RegisterClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ssosage_RegisterClient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SsosageServer).RegisterClient(ctx, req.(*RegisterClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ssosage_GenerateToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SsosageServer).GenerateToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ssosage_GenerateToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SsosageServer).GenerateToken(ctx, req.(*GenerateTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Ssosage_ServiceDesc is the grpc.ServiceDesc for Ssosage service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Ssosage_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ssosage_proto.Ssosage",
	HandlerType: (*SsosageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterApp",
			Handler:    _Ssosage_RegisterApp_Handler,
		},
		{
			MethodName: "RegisterClient",
			Handler:    _Ssosage_RegisterClient_Handler,
		},
		{
			MethodName: "GenerateToken",
			Handler:    _Ssosage_GenerateToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ssosage.proto",
}
